# Configuration file for deploying the OCR function using nuctl
# To deploy the function using the UI, just copy the python code
# from function.py and the build commands from this file
#
# TODO test!

apiVersion: "nuclio.io/v1beta1" # TODO ??
kind: "NuclioFunction"
spec:
  description: > 
    Performs OCR on a PDF file. The input PDF has to be stored in the minio profaastinate bucket.
    Headers:
    - 'X-OCR-Filename': 'test.pdf'
    - 'forceOCR': 'True'
  runtime: "python" # TODO test whether this should be python3.9
  handler: "ocr:ocr"
  minReplicas: 1
  maxReplicas: 1

  build:
    commands:
    - "apt-get update"
    - "apt-get install ocrmypdf -y"
    - "pip install pytesseract"
    - "pip install ocrmypdf"
    - "pip install minio"
    - "pip install pdfminer" # TODO this should not be required?
